version: ~> 1.0
sudo: required
dist: xenial
language: python

python:
  - "3.7"

# run unit tests
# Build image
# smoke test
# integration test
# deploy

stages:
  - lint
  - unittest
  # - name: deploy
  #   if: tag IS present

# notifications:
#   email:
#     on_failure: always
#     recipients:
#       - brock@driftwoodenergy.com

# cache:
#   apt: true
#   directories:
#     - "$HOME/.cache/pip"

# services:
#   - docker
#   - mongodb
#   - redis

env:
  global:
    - PYCURL_SSL_LIBRARY=openssl
    # - PATH=$HOME/.local/bin:$PATH
    # - PATH "/root/.poetry/bin:/opt/venv/bin:${PATH}"

before_install:
  # - sudo apt-get update
  # - pip install pycurl
  - pip install awscli
  - pip install boto3
  - pip install poetry
  - pip install docker
  # - pip install pre-commit

install:
  - poetry install -v

# before_script:
#   - poetry run pre-commit install-hooks
#   - poetry run pre-commit run --all-files

# script:
#   - poetry run pytest --doctest-modules --cov-report term-missing --cov-report html:htmlcov --cov=src/cltkv1 src/cltkv1/ tests

jobs:
  include:
    - stage: lint
      script: pylint ihs
    - stage: test
      script: make run-tests
      # name: build-backend-dev
      # if: branch = development
      # script: travis_wait make dev login backend build push

# after_success: poetry run coveralls
