version: "3.7"

x-defaults: &defaults
  image: driftwood/ihs:latest
  restart: unless-stopped
  env_file: .env.compose
  volumes:
    - ./:/app
  depends_on:
    - redis

services:
  web:
    <<: *defaults
    command: ihs run web
    ports:
      - 5000
  worker:
    <<: *defaults
    command: ihs run worker -Q ihs-default,ihs-submissions-h,ihs-collections-h,ihs-deletions-h,ihs-submissions-v,ihs-collections-v,ihs-deletions-v --loglevel DEBUG
  cron:
    <<: *defaults
    command: ihs run cron --loglevel=DEBUG
  redis:
    container_name: ihs_redis
    image: redis
    command: redis-server  --save "" --appendonly no --loglevel notice --bind 0.0.0.0
    ports:
      - 6379
