version: "3.7"

x-defaults: &defaults
  image: ihs-deo
  # build:
  #   context: .
  #   dockerfile: Dockerfile
  restart: unless-stopped
  env_file:
    - .env

services:
  # web:
  #   <<: *defaults
  #   user: celeryuser
  #   command: iwell run web
  #   ports:
  #     - "5000:5000"
  worker:
    <<: *defaults
    command: ihs run worker -Q ihs-collector,ihs-collections
    ports:
      - 5000
  worker:
    <<: *defaults
    command: ihs run worker -Q ihs-collector,ihs-collections
    ports:
      - 5000
  cron:
    <<: *defaults
    command: ihs run cron --loglevel=DEBUG
