version: "3.7"

x-defaults: &defaults
  image: driftwood/ihs:latest
  # build:
  #   context: .
  #   dockerfile: Dockerfile
  restart: unless-stopped
  # environment:
  #   - AWS_REGION
  #   - AWS_ACCESS_KEY_ID
  #   - AWS_SECRET_ACCESS_KEY
  #   - AWS_SESSION_TOKEN
  #   - AWS_SECURITY_TOKEN
  env_file: .env.compose

services:
  web:
    <<: *defaults
    command: ihs run web
    ports:
      - "5000:5000"
  worker:
    <<: *defaults
    command: ihs run worker -Q ihs-default,ihs-submissions-h,ihs-collections-h,ihs-deletions-h,ihs-submissions-v,ihs-collections-v,ihs-deletions-v --loglevel DEBUG
  cron:
    <<: *defaults
    command: ihs run cron --loglevel=DEBUG
