version: "3.7"

x-defaults: &defaults
  image: driftwood/ihs:latest
  restart: unless-stopped
  env_file: .env.compose
  volumes:
    - ./:/app
    - ./tests/data/collector.yaml:/app/config/collector.yaml
  depends_on:
    - redis

services:
  web:
    <<: *defaults
    command: ihs run web
    ports:
      - 5000
  ihs_worker_1:
    <<: *defaults
    container_name: ihs_worker_1
    user: celeryuser
    command: ihs run worker -Q ihs-default,ihs-submissions-h,ihs-collections-h,ihs-deletions-h,ihs-submissions-v,ihs-collections-v,ihs-deletions-v
  ihs_worker_2:
    <<: *defaults
    container_name: ihs_worker_2
    user: celeryuser
    command: ihs run worker -Q ihs-default,ihs-submissions-h,ihs-collections-h,ihs-deletions-h,ihs-submissions-v,ihs-collections-v,ihs-deletions-v
  cron:
    <<: *defaults
    command: ihs run cron --pidfile=
  redis:
    container_name: ihs_redis
    image: redis
    command: redis-server  --save "" --appendonly no --loglevel notice --bind 0.0.0.0
    ports:
      - 6379:6379
