version: "3.7"

x-defaults: &defaults
  image: ihs-deo
  # build:
  #   context: .
  #   dockerfile: Dockerfile
  restart: unless-stopped
  environment:
    - AWS_REGION
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - AWS_SECURITY_TOKEN

services:
  web:
    <<: *defaults
    # user: celeryuser
    command: ihs run web
    # command: pwd
    ports:
      - "5000:5000"
  worker:
    <<: *defaults
    command: ihs run worker
    # entrypoint:
  # cron:
  #   <<: *defaults
  #   command: ihs run cron --loglevel=DEBUG
