[tool.poetry]
name = "ihs"
version = "0.1.0"
description = ""
authors = ["Brock Friedrich <brock@driftwoodenergy.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "*"
pandas = "*"
sentry-sdk = "*"
oauthlib = "*"
click = "*"
flask = "*"
flask-debugtoolbar = "*"
Flask-RESTful = "*"
python-dotenv = "^0.10.3"
attrdict = "^2.0"
tomlkit = "^0.5.8"
logutils = "^0.3.5"
pyparsing = "^2.4"
attrs = "^19.3"
datadog = "^0.31.0"
celery = {version = "^4.3.0", extras = ["sqs"]}
pymongo = "^3.9.0"
zeep = "*"
lxml = "^4.4.1"
mongoengine = "^0.18.2"
flask-mongoengine = "^0.9.5"
requests_oauthlib = "^1.3.0"
xmltodict = "^0.12.0"
marshmallow = "^3.2.2"
pyproj = "^2.4.1"
gunicorn = "^20.0.4"
JSON-log-formatter = "^0.2.0"
ddtrace = "^0.31.0"


[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
mypy = "*"
pylint = "*"
ipython = "*"
matplotlib = "*"
pytest = "*"
pytest-cov = "*"
coverage = "*"
docker = "*"
boto3 = "*"
hypothesis = "*"
requests-mock = "*"
requests_mock = "*"
redis = "^3.3.11"

[tool.poetry.scripts]
ihs = "ihs.manage:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


