version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  docker: circleci/docker@0.5.19

jobs:
  # Building and testing the project
  # Useful when a PR is open, for example
  run-tests:
    docker:
      - image: circleci/python:3.7

    # The steps for our run-tests
    steps:
      # Get the code
      - checkout

      # Cache can be tricky at first, but this means

      # Please, restore my cache (what is actually on the cache will be defined later)
      # if the text key `deps-{{ checksum "poetry.lock" }}` changes (and it WILL change everytime poetry.lock is updated since we rely on its checksum)
      # and poetry.lock is updated every time we add a new dependency to our project
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      # Let's install the dependencies
      - run:
          name: Install Dependencies
          command: poetry install

      # Save's the specified path as a cache. This is the path Poetry uses to install the dependencies
      # So if you don't install anything new, this folder won't change and the cache will be effective
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: lint
          command: poetry run pylint ihs --exit-zero --rcfile=.pylintrc

      - run:
          name: CodeClimate before-build
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run python tests
          command: poetry run pytest --cov=ihs tests/ --cov-report xml:./coverage/python/coverage.xml
      - run:
          name: CodeClimate combine and upload coverage
          command: |
            # Format the various coverage reports
            ./cc-test-reporter format-coverage -t coverage.py -o coverage/codeclimate.python.json coverage/python/coverage.xml
            # Combine the test coverage reports
            ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
            # Attempt to submit the coverage report, but don't fail the build if this fails (`|| true`)
            ./cc-test-reporter upload-coverage || true

      - codecov/upload:
          file: ./coverage/python/coverage.xml

  build-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/publish:
          image: driftwood/ihs
          tag: ${CIRCLE_SHA1}, dev
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  publish-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/publish:
          image: driftwood/ihs
          tag: latest, ${CIRCLE_TAG}
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} .

  # This is the definition of another job, the one we use to publish the package to PyPI
  deployment:
    # Same environment
    docker:
      - image: circleci/python:3.7
    steps:
      # Gets the code
      - checkout
        # Use `poetry publish` to Publish the package using username and password from CircleCI environment variables
        # Which can be configured inside CircleCI's interface
        # - run:
        #     name: Push to PyPI
        #     command: |
        #       poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

# In the workflows section, we specify when we want to run the jobs defined
workflows:
  version: 2.1

  # The run-tests we will run EVERYTIME a piece of code changes
  test-and-build-workflow:
    jobs:
      - run-tests
      - build-image

  # The deployment workflow publishes the package
  deployment-workflow:
    jobs:
      - publish-github-release:
          requires:
            - run-tests
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

      # Runs the deployment job, just with the tags as well
      - publish-image:
          requires:
            - run-tests
            - build-image
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
