default_schedule: &default_schedule # seconds: 15
  cron:
    minute: "*/30"

job_defaults:
  sync: &default_sync
    mode: sync
    cron:
      minute: 0
      hour: 0
  # hourly:
  #   mode:
  full: &default_full
    mode: full
    cron:
      minute: 0
      hour: 0

default_aliases: &default_aliases
  created_at: ihs_created_at
  updated_at: ihs_updated_at

default_status: &default_status
  enabled: true

endpoints:
  wells:
    enabled: true
    version: v10
    model: api.models.Well
    exclude: []
    normalize: false
    options:
      data_type: Well
    tasks:
      sync:
        <<: *default_sync
        options:
          query_path: config/queries/well-driftwood.xml
          template_path: config/templates/well.xml
      full:
        <<: *default_full
  production_allocated:
    enabled: true
    version: v10
    model: api.models.ProductionAllocated
    exclude: []
    normalize: false
    options:
      data_type: Production Allocated
    tasks:
      sync:
        <<: *default_sync
        options:
          query_path: config/queries/well-driftwood.xml
          template_path: config/templates/well.xml
      full:
        <<: *default_full
