default_schedule: &default_schedule # seconds: 15
  cron:
    minute: "*/30"

job_defaults:
  sync: &default_sync
    mode: sync
    seconds: 360
  full: &default_full
    mode: full
    cron:
      minute: 0
      hour: 0

default_aliases: &default_aliases
  created_at: ihs_created_at
  updated_at: ihs_updated_at

default_status: &default_status
  enabled: true

counties: &counties
  # tx-andrews:
  #   county_code: "003"
  #   state_code: 42
  # tx-bailey:
  #   county_code: "017"
  #   state_code: 42
  # tx-crosby:
  #   county_code: 107
  #   state_code: 42
  # tx-borden:
  #   county_code: "033"
  #   state_code: 42
  # tx-brown:
  #   county_code: "049"
  #   state_code: 42
  # tx-cochran:
  #   county_code: "079"
  #   state_code: 42
  # tx-dawson:
  #   county_code: 115
  #   state_code: 42
  # tx-coke:
  #   county_code: "081"
  #   state_code: 42
  # tx-concho:
  #   county_code: "095"
  #   state_code: 42
  # tx-cottle:
  #   county_code: 101
  #   state_code: 42
  # tx-crane:
  #   county_code: 103
  #   state_code: 42
  # tx-crockett:
  #   county_code: 105
  #   state_code: 42
  # tx-dickens:
  #   county_code: 125
  #   state_code: 42
  # tx-ector:
  #   county_code: 135
  #   state_code: 42
  # tx-garza:
  #   county_code: 169
  #   state_code: 42
  # tx-floyd:
  #   county_code: 153
  #   state_code: 42
  # tx-gaines:
  #   county_code: 165
  #   state_code: 42
  # tx-glasscock:
  #   county_code: 173
  #   state_code: 42
  # tx-hale:
  #   county_code: 189
  #   state_code: 42
  # tx-hockley:
  #   county_code: 219
  #   state_code: 42
  # tx-taylor:
  #   county_code: 441
  #   state_code: 42
  # tx-howard:
  #   county_code: 227
  #   state_code: 42
  # tx-irion:
  #   county_code: 235
  #   state_code: 42
  # tx-kent:
  #   county_code: 263
  #   state_code: 42
  # tx-kimble:
  #   county_code: 267
  #   state_code: 42
  # tx-king:
  #   county_code: 269
  #   state_code: 42
  # tx-lamb:
  #   county_code: 279
  #   state_code: 42
  # tx-lubbock:
  #   county_code: 303
  #   state_code: 42
  # tx-lynn:
  #   county_code: 305
  #   state_code: 42
  # tx-martin:
  #   county_code: 317
  #   state_code: 42
  # tx-mcculloch:
  #   county_code: 307
  #   state_code: 42
  # tx-menard:
  #   county_code: 327
  #   state_code: 42
  # tx-midland:
  #   county_code: 329
  #   state_code: 42
  # tx-mitchell:
  #   county_code: 335
  #   state_code: 42
  # tx-motley:
  #   county_code: 345
  #   state_code: 42
  tx-reagan:
    county_code: 383
    state_code: 42
  # tx-runnels:
  #   county_code: 399
  #   state_code: 42
  # tx-schleicher:
  #   county_code: 413
  #   state_code: 42
  # tx-scurry:
  #   county_code: 415
  #   state_code: 42
  # tx-sterling:
  #   county_code: 431
  #   state_code: 42
  # tx-stonewall:
  #   county_code: 433
  #   state_code: 42
  # tx-sutton:
  #   county_code: 435
  #   state_code: 42
  # tx-terry:
  #   county_code: 445
  #   state_code: 42
  # tx-tomgreen:
  #   county_code: 451
  #   state_code: 42
  tx-upton:
    county_code: 461
    state_code: 42
  # tx-yoakum:
  #   county_code: 501
  #   state_code: 42

endpoints:
  # well_master_horizontal:
  #   enabled: true
  #   version: v10
  #   model: api.models.WellMasterHorizontal
  #   exclude: []
  #   normalize: false
  #   propagate_to_task: true
  #   options:
  #     data_type: Well
  #     template: Well ID List
  #     criteria:
  #       hole_direction: H
  #   tasks:
  #     sync:
  #       seconds: 60
  #       # cron:
  #       #   minute: 0
  #       #   hour: 0
  #       options:
  #         query_path: well_horizontal_by_county.xml
  #         matrix:
  #           <<: *counties
  # full:
  #   <<: *default_full
  well_horizontal:
    enabled: true
    version: v10
    model: api.models.WellHorizontal
    exclude: []
    normalize: false
    options:
      data_type: Well
      template: EnerdeqML Well
      criteria:
        hole_direction: H
    tasks:
      sync:
        seconds: 30
        options:
          query_path: well_by_api.xml
          matrix:
            using: api.models.WellMasterHorizontal.ids
            label: api
      sequoia:
        seconds: 30
        options:
          query_path: well_by_api.xml
          matrix:
            sequoia:
              api: "42461409160000"
  # well_master_vertical:
  #   enabled: true
  #   version: v10
  #   model: api.models.WellMasterVertical
  #   exclude: []
  #   normalize: false
  #   propagate_to_task: true
  #   options:
  #     data_type: Well
  #     template: Well ID List
  #     criteria:
  #       hole_direction: V
  #   tasks:
  #     sync:
  #       seconds: 60
  #       # cron:
  #       #   minute: 0
  #       #   hour: 0
  #       options:
  #         query_path: well_vertical_by_county.xml
  #         matrix:
  #           <<: *counties
  # well_vertical:
  #   enabled: true
  #   version: v10
  #   model: api.models.WellVertical
  #   exclude: []
  #   normalize: false
  #   options:
  #     data_type: Well
  #     template: EnerdeqML Well
  #     criteria:
  #       hole_direction: V
  #   tasks:
  #     sync:
  #       <<: *default_sync
  #       options:
  #         query_path: well_vertical_by_county.xml
  #         matrix:
  #           <<: *counties
  #     # driftwood:
  #     #   <<: *default_sync
  #     #   options:
  #     #     query_path: well_vertical_driftwood_all.xml
  production_horizontal:
    enabled: true
    version: v10
    model: api.models.ProductionHorizontal
    exclude: []
    normalize: false
    options:
      data_type: Production Allocated
      template: EnerdeqML Production
      criteria:
        hole_direction: H
    tasks:
      sequoia:
        seconds: 30
        options:
          query_path: production_by_api.xml
          matrix:
            sequoia:
              api: "42461409160000"
