default_schedule: &default_schedule # seconds: 15
  cron:
    minute: "*/30"

job_defaults:
  sync: &default_sync
    mode: sync
    cron:
      minute: 0
      hour: 0
  # hourly:
  #   mode:
  full: &default_full
    mode: full
    cron:
      minute: 0
      hour: 0

default_aliases: &default_aliases
  created_at: ihs_created_at
  updated_at: ihs_updated_at

default_status: &default_status
  enabled: true

counties: &counties
  tx-andrews:
    county_code: 003
    state_code: 42
  tx-hall:
    county_code: 191
    state_code: 42
  tx-hardeman:
    county_code: 197
    state_code: 42
  tx-bailey:
    county_code: 017
    state_code: 42
  tx-crosby:
    county_code: 107
    state_code: 42
  tx-borden:
    county_code: 033
    state_code: 42
  tx-briscoe:
    county_code: 045
    state_code: 42
  tx-brown:
    county_code: 049
    state_code: 42
  tx-childress:
    county_code: 075
    state_code: 42
  tx-cochran:
    county_code: 079
    state_code: 42
  tx-foard:
    county_code: 155
    state_code: 42
  tx-dawson:
    county_code: 115
    state_code: 42
  tx-coke:
    county_code: 081
    state_code: 42
  tx-gillespie:
    county_code: 171
    state_code: 42
  tx-coleman:
    county_code: 083
    state_code: 42
  tx-concho:
    county_code: 095
    state_code: 42
  tx-cottle:
    county_code: 101
    state_code: 42
  tx-crane:
    county_code: 103
    state_code: 42
  tx-crockett:
    county_code: 105
    state_code: 42
  tx-dickens:
    county_code: 125
    state_code: 42
  tx-ector:
    county_code: 135
    state_code: 42
  tx-edwards:
    county_code: 137
    state_code: 42
  tx-fisher:
    county_code: 151
    state_code: 42
  tx-kerr:
    county_code: 265
    state_code: 42
  tx-garza:
    county_code: 169
    state_code: 42
  tx-floyd:
    county_code: 153
    state_code: 42
  tx-gaines:
    county_code: 165
    state_code: 42
  tx-glasscock:
    county_code: 173
    state_code: 42
  tx-hale:
    county_code: 189
    state_code: 42
  tx-hockley:
    county_code: 219
    state_code: 42
  tx-taylor:
    county_code: 441
    state_code: 42
  tx-howard:
    county_code: 227
    state_code: 42
  tx-irion:
    county_code: 235
    state_code: 42
  tx-kent:
    county_code: 263
    state_code: 42
  tx-kimble:
    county_code: 267
    state_code: 42
  tx-king:
    county_code: 269
    state_code: 42
  tx-knox:
    county_code: 275
    state_code: 42
  tx-lamb:
    county_code: 279
    state_code: 42
  tx-lubbock:
    county_code: 303
    state_code: 42
  tx-lynn:
    county_code: 305
    state_code: 42
  tx-martin:
    county_code: 317
    state_code: 42
  tx-mason:
    county_code: 319
    state_code: 42
  tx-mcculloch:
    county_code: 307
    state_code: 42
  tx-menard:
    county_code: 327
    state_code: 42
  tx-midland:
    county_code: 329
    state_code: 42
  tx-mitchell:
    county_code: 335
    state_code: 42
  tx-motley:
    county_code: 345
    state_code: 42
  tx-nolan:
    county_code: 353
    state_code: 42
  tx-reagan:
    county_code: 383
    state_code: 42
  tx-runnels:
    county_code: 399
    state_code: 42
  tx-san saba:
    county_code: 411
    state_code: 42
  tx-schleicher:
    county_code: 413
    state_code: 42
  tx-scurry:
    county_code: 415
    state_code: 42
  tx-sterling:
    county_code: 431
    state_code: 42
  tx-stonewall:
    county_code: 433
    state_code: 42
  tx-sutton:
    county_code: 435
    state_code: 42
  tx-terry:
    county_code: 445
    state_code: 42
  tx-tom green:
    county_code: 451
    state_code: 42
  tx-upton:
    county_code: 461
    state_code: 42
  tx-val verde:
    county_code: 465
    state_code: 42
  tx-yoakum:
    county_code: 501
    state_code: 42

endpoints:
  wells:
    enabled: true
    version: v10
    model: api.models.Well
    exclude: []
    normalize: false
    options:
      data_type: Well
      template: EnerdeqML Well
    tasks:
      driftwood:
        <<: *default_sync
        options:
          query_path: well_driftwood_all.xml
      sync_identities:
        cron:
          minute: 0
          hour: 0
        options:
          query_path: well_horizontal_by_county.xml
          matrix:
            <<: *counties
      full:
        <<: *default_full
  production:
    enabled: true
    version: v10
    model: api.models.ProductionAllocated
    exclude: []
    normalize: false
    options:
      data_type: Production Allocated
      template: EnerdeqML Production
    tasks:
      driftwood:
        <<: *default_sync
        options:
          query_path: production_driftwood_all.xml
      full:
        <<: *default_full
