every_minute: &every_minute
  seconds: 60

nightly: &nightly # <<: *every_minute
  cron:
    minute: 0
    hour: 3

every_6_hours: &every_6_hours # <<: *every_minute
  cron:
    minute: 0
    hour: "*/6"

weekly: &weekly # <<: *every_minute
  cron:
    minute: 0
    hour: 16
    day_of_week: 5

default_aliases: &default_aliases
  created_at: ihs_created_at
  updated_at: ihs_updated_at

default_status: &default_status
  enabled: true

counties: &counties
  tx-upton:
    county_code: 461
    state_code: 42
  tx-reagan:
    county_code: 383
    state_code: 42
  tx-midland:
    county_code: 329
    state_code: 42
  tx-glasscock:
    county_code: 173
    state_code: 42
  tx-andrews:
    county_code: "003"
    state_code: 42
  tx-bailey:
    county_code: "017"
    state_code: 42
  tx-crosby:
    county_code: 107
    state_code: 42
  tx-borden:
    county_code: "033"
    state_code: 42
  tx-brown:
    county_code: "049"
    state_code: 42
  tx-cochran:
    county_code: "079"
    state_code: 42
  tx-dawson:
    county_code: 115
    state_code: 42
  tx-coke:
    county_code: "081"
    state_code: 42
  tx-concho:
    county_code: "095"
    state_code: 42
  tx-cottle:
    county_code: 101
    state_code: 42
  tx-crane:
    county_code: 103
    state_code: 42
  tx-crockett:
    county_code: 105
    state_code: 42
  tx-dickens:
    county_code: 125
    state_code: 42
  tx-ector:
    county_code: 135
    state_code: 42
  tx-garza:
    county_code: 169
    state_code: 42
  tx-floyd:
    county_code: 153
    state_code: 42
  tx-gaines:
    county_code: 165
    state_code: 42
  tx-hale:
    county_code: 189
    state_code: 42
  tx-hockley:
    county_code: 219
    state_code: 42
  tx-taylor:
    county_code: 441
    state_code: 42
  tx-howard:
    county_code: 227
    state_code: 42
  tx-irion:
    county_code: 235
    state_code: 42
  tx-kent:
    county_code: 263
    state_code: 42
  tx-kimble:
    county_code: 267
    state_code: 42
  tx-king:
    county_code: 269
    state_code: 42
  tx-lamb:
    county_code: 279
    state_code: 42
  tx-lubbock:
    county_code: 303
    state_code: 42
  tx-lynn:
    county_code: 305
    state_code: 42
  tx-martin:
    county_code: 317
    state_code: 42
  tx-mcculloch:
    county_code: 307
    state_code: 42
  tx-menard:
    county_code: 327
    state_code: 42
  tx-mitchell:
    county_code: 335
    state_code: 42
  tx-motley:
    county_code: 345
    state_code: 42
  tx-runnels:
    county_code: 399
    state_code: 42
  tx-schleicher:
    county_code: 413
    state_code: 42
  tx-scurry:
    county_code: 415
    state_code: 42
  tx-sterling:
    county_code: 431
    state_code: 42
  tx-stonewall:
    county_code: 433
    state_code: 42
  tx-sutton:
    county_code: 435
    state_code: 42
  tx-terry:
    county_code: 445
    state_code: 42
  tx-tomgreen:
    county_code: 451
    state_code: 42
  tx-yoakum:
    county_code: 501
    state_code: 42

endpoints:
  well_master_horizontal:
    enabled: true
    version: v10
    model: api.models.WellMasterHorizontal
    exclude: []
    normalize: false
    propagate_to_task: true
    options:
      data_type: Well
      template: Well ID List
      criteria:
        hole_direction: H
        operator: 278107
    tasks:
      sync:
        cron:
          minute: "*/15"
        options:
          query_path: well_horizontal_by_county.xml
          matrix:
            <<: *counties

  well_horizontal:
    enabled: true
    version: v10
    model: api.models.WellHorizontal
    exclude: []
    normalize: false
    options:
      data_type: Well
      template: EnerdeqML Well
      criteria:
        hole_direction: H
    tasks:
      sync:
        <<: *nightly
        options:
          query_path: well_by_api.xml
          matrix:
            using: api.models.WellMasterHorizontal.ids
            label: api
      driftwood:
        seconds: 300
        options:
          query_path: well_horizontal_driftwood_all.xml
      # sequoia:
      #   seconds: 300
      #   options:
      #     query_path: well_by_api.xml
      #     matrix:
      #       sequoia:
      #         api: "42461409160000"

  production_master_horizontal:
    enabled: true
    version: v10
    model: api.models.ProductionMasterHorizontal
    exclude: []
    normalize: false
    propagate_to_task: true
    options:
      data_type: Production Allocated
      template: Production ID List
      criteria:
        hole_direction: H
    tasks:
      sync:
        cron:
          minute: "*/15"
        options:
          query_path: production_horizontal_by_county.xml
          matrix:
            <<: *counties
      # check_for_new:
      # TODO: Check for wells in master list that arent in database and download them

  production_horizontal:
    enabled: true
    version: v10
    model: api.models.ProductionHorizontal
    exclude: []
    normalize: false
    options:
      data_type: Production Allocated
      template: EnerdeqML Production
      criteria:
        hole_direction: H
    tasks:
      sync:
        <<: *nightly
        options:
          query_path: production_by_entity.xml
          matrix:
            using: api.models.ProductionMasterHorizontal.ids
            label: producing_entity
      sequoia:
        enabled: false
        seconds: 300
        options:
          query_path: production_by_api.xml
          matrix:
            sequoia:
              api: "42461409160000"
      # welllist:
      #   seconds: 300
      #   options:
      #     query_path: production_by_api.xml
      #     matrix:
      #       api:
      #         - 42461409160000
      #         - 42461409160001
      #         - 42461409160002
      #         - 42461409160003
      #         - 42461409160004

  well_master_vertical:
    enabled: true
    version: v10
    model: api.models.WellMasterVertical
    exclude: []
    normalize: false
    propagate_to_task: true
    options:
      data_type: Well
      template: Well ID List
      criteria:
        hole_direction: V
    tasks:
      sync:
        cron:
          minute: "*/15"
        options:
          query_path: well_vertical_by_county.xml
          matrix:
            <<: *counties

  well_vertical:
    enabled: true
    version: v10
    model: api.models.WellVertical
    exclude: []
    normalize: false
    options:
      data_type: Well
      template: EnerdeqML Well
      criteria:
        hole_direction: V
    tasks:
      sync:
        <<: *nightly
        options:
          query_path: well_by_api.xml
          matrix:
            using: api.models.WellMasterVertical.ids
            label: api
      driftwood:
        seconds: 300
        options:
          query_path: well_vertical_driftwood_all.xml
      # check_for_new:
      # TODO: Check for wells in master list that arent in database and download them

  production_master_vertical:
    enabled: true
    version: v10
    model: api.models.ProductionMasterVertical
    exclude: []
    normalize: false
    propagate_to_task: true
    options:
      data_type: Production Allocated
      template: Production ID List
      criteria:
        hole_direction: V
    tasks:
      sync:
        cron:
          minute: "*/15"
        options:
          query_path: production_vertical_by_county.xml
          matrix:
            <<: *counties

  production_vertical:
    enabled: true
    version: v10
    model: api.models.ProductionVertical
    exclude: []
    normalize: false
    options:
      data_type: Production Allocated
      template: EnerdeqML Production
      criteria:
        hole_direction: V
    tasks:
      sync:
        <<: *nightly
        options:
          query_path: production_by_entity.xml
          matrix:
            using: api.models.ProductionMasterVertical.ids
            label: producing_entity
      driftwood:
        seconds: 300
        options:
          query_path: well_vertical_driftwood_all.xml
