version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s:%(name)s:%(funcName)s() - %(message)s"
    detail:
        format: "[%(levelname)s: %(asctime)s - %(filename)s:%(lineno)s:%(name)s:%(funcName)s()]  - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    threadded:
        format: "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detail
        stream: ext://sys.stdout

loggers:
    main:
        level: DEBUG
        handlers: [console]
        propagate: True

    zeep:
        level: WARNING
        handlers: [console]
        propagate: True

    datadog:
        level: ERROR
        handlers: [console]
        propagate: True
