parsers:
  default:
    rules:
      - name: match_int_float_isodate
        allow_partial: true
        criteria:
          - name: match_float
            type: RegexCriterion
            # value: ^[-+]?[0-9]*\.[0-9]+$
            value: ^[-+]?\d*\.\d+|\d+$
          - name: match_int
            type: RegexCriterion
            value: ^[-+]?[0-9]+$
          - name: match_isodate
            type: RegexCriterion
            value: ^\d\d\d\d-\d\d-\d\d$
